// api/index.js
const urls = [
  "https://google.com",
  "https://youtube.com",
  "https://github.com",
  "https://stackoverflow.com",
  "https://reddit.com",
  "https://twitter.com",
  "https://facebook.com",
  "https://instagram.com",
  "https://linkedin.com",
  "https://tiktok.com",
  "https://telegram.org",
  "https://whatsapp.com",
  "https://discord.com",
  "https://slack.com",
  "https://zoom.us",
  "https://notion.so",
  "https://trello.com",
  "https://figma.com",
  "https://canva.com",
  "https://dropbox.com",
  "https://drive.google.com",
  "https://onedrive.live.com",
  "https://mega.nz",
  "https://pinterest.com",
  "https://tumblr.com",
  "https://vimeo.com",
  "https://twitch.tv",
  "https://spotify.com",
  "https://soundcloud.com",
  "https://bandcamp.com",
  "https://medium.com",
  "https://dev.to",
  "https://hashnode.com",
  "https://producthunt.com",
  "https://hackernews.com",
  "https://arxiv.org",
  "https://wikipedia.org",
  "https://archive.org",
  "https://coursera.org",
  "https://udemy.com",
  "https://edx.org",
  "https://khanacademy.org",
  "https://codecademy.com",
  "https://freecodecamp.org",
  "https://leetcode.com",
  "https://codewars.com",
  "https://hackerrank.com",
  "https://amazon.com",
  "https://ebay.com",
  "https://aliexpress.com",
  "https://etsy.com",
  "https://shopify.com",
  "https://wix.com",
  "https://wordpress.com",
  "https://squarespace.com",
  "https://webflow.com",
  "https://netlify.com",
  "https://cloudflare.com",
  "https://aws.amazon.com",
  "https://cloud.google.com",
  "https://azure.microsoft.com",
  "https://digitalocean.com",
  "https://heroku.com",
  "https://railway.app",
  "https://render.com",
  "https://fly.io",
  "https://supabase.com",
  "https://firebase.google.com",
  "https://mongodb.com",
  "https://redis.com",
  "https://stripe.com",
  "https://paypal.com",
  "https://coinbase.com",
  "https://binance.com",
  "https://openai.com"
];

module.exports = (req, res) => {
  // Выбираем случайный URL из массива
  const randomUrl = urls[Math.floor(Math.random() * urls.length)];
  
  // Делаем редирект (302 = временный)
  res.writeHead(302, { Location: randomUrl });
  res.end();
};